
drop table if exists PLAYERS;
drop table if exists TEAMLEADERS;
drop table if exists TEAMLEADERPLAYER;

create table PLAYERS(
  idplayer int not null AUTO_INCREMENT,
  name varchar(100) not null,
  team varchar(100) not null,
  quote int not null,
  role varchar(1) not null,
  fvm int,
  PRIMARY KEY ( idplayer )
);

create table TEAMLEADERS(
  idteamleader int not null AUTO_INCREMENT,
  name varchar(100) not null,
  teamname varchar(100) not null,
  PRIMARY KEY ( idteamleader )
);

create table TEAMLEADERPLAYER(
  idteamleaderplayer int not null AUTO_INCREMENT,
  idteamleader int not null,
  idplayer int not null,
  PRIMARY KEY ( idteamleaderplayer )
);


INSERT INTO TEAMLEADERS (name, teamname) VALUES ('Roberto', 'I Macellai');
INSERT INTO TEAMLEADERS (name, teamname)VALUES ('Enrico', 'Sorci Verdi Bisceglie');
INSERT INTO TEAMLEADERS (name, teamname) VALUES ('Davide', 'PoltroneNzolà');
INSERT INTO TEAMLEADERS (name, teamname) VALUES ('Vanni', 'Real Rainmakers');
INSERT INTO TEAMLEADERS (name, teamname) VALUES ('Francesco', 'Pescaramanzia');
INSERT INTO TEAMLEADERS (name, teamname) VALUES ('Nicola', 'AC Nicola');
INSERT INTO TEAMLEADERS (name, teamname) VALUES ('Carlo', 'A Testa Alta');
INSERT INTO TEAMLEADERS (name, teamname) VALUES ('Leo', 'ci penso');

INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Meret','Napoli',17,80);								    
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Maignan','Milan',17,89                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Provedel','Lazio',16,68                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Szczesny','Rubentus',15,71                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Sommer','Inter',15,67                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Rui Patricio','Roma',14,59                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Di Gregorio','Monza',12,37                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Carnesecchi','Atalanta',11,38               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Skorupski','Bologna',10,32                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Milinkovic-Savic V.','Torino',10,31         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Terracciano','Fiorentina',10,31             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Silvestri','Udinese',9,31                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Ochoa','Salernitana',9,30                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Radunovic','Cagliari',8,16                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Falcone','Lecce',8,22                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Martinez Jo.','Genoa',8,15                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Caprile','Empoli',7,14                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Montipo''','Verona',7,13                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Consigli','Sassuolo',5,15                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Turati','Frosinone',5,6                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Cragno','Sassuolo',4,8                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Musso','Atalanta',3,15                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Christensen O.','Fiorentina',3,5                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Perisan','Empoli',2,3                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Sportiello','Milan',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Mirante','Milan',1,1                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Sepe','Salernitana',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Leali','Genoa',1,1                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Lamanna','Monza',1,1                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Perin','Rubentus',1,5                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Sommariva','Genoa',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Pegolo','Sassuolo',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Perilli','Verona',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Padelli','Udinese',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Scuffet','Cagliari',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Gollini','Napoli',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Audero','Inter',1,1                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Di Gennaro','Inter',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Pinsoglio','Rubentus',1,1                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Aresti','Cagliari',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Fiorillo','Salernitana',1,1                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Cerofolini','Frosinone',1,1                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Rossi F.','Atalanta',1,1                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Costil','Salernitana',1,1                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Ravaglia F.','Bologna',1,1                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Contini','Napoli',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Brancolini','Lecce',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Berardi A.','Verona',1,1                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Gemello','Torino',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Boer','Roma',1,1                                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Adamonis','Lazio',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Piana','Udinese',1,1                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Bagnolini','Bologna',1,1                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Svilar','Roma',1,1                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Sorrentino A.','Monza',1,1                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Martinelli T.','Fiorentina',1,1                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Popa','Torino',1,1                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Stubljar','Empoli',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Gori','Monza',1,1                               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Borbei','Lecce',1,1                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('P','Palmisani','Frosinone',1,1                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Dimarco','Inter',19,81                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Di Lorenzo','Napoli',18,75                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Hernandez T.','Milan',17,83                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Carlos Augusto','Inter',17,42               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Posch','Bologna',16,53                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Zappacosta','Atalanta',15,48                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Danilo','Rubentus',15,44                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Smalling','Roma',15,55                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Rrahmani','Napoli',14,44                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Schuurs','Torino',14,46                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Romagnoli','Lazio',13,36                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bastoni','Inter',13,43                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bremer','Rubentus',13,48                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Tomori','Milan',13,43                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bakker','Atalanta',12,42                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Mazzocchi','Salernitana',12,37              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Dumfries','Inter',12,47                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Acerbi','Inter',11,32                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Mancini','Roma',11,26                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Darmian','Inter',11,30                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Buongiorno','Torino',11,23                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ebuehi','Empoli',11,17                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Doig','Verona',11,20                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Mario Rui','Napoli',10,24                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Biraghi','Fiorentina',10,24                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Spinazzola','Roma',10,26                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Milenkovic','Fiorentina',10,25              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Casale','Lazio',10,24                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Baschirotto','Lecce',10,33                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Thiaw','Milan',10,27                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Calabria','Milan',9,22                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Faraoni','Verona',9,18                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Toloi','Atalanta',9,19                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Cuadrado','Inter',9,34                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Kolasinac','Atalanta',9,20                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','N''dicka','Roma',9,24                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Kyriakopoulos','Monza',9,15                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Mari''','Monza',9,18                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Scalvini','Atalanta',9,30                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Perez N.','Udinese',9,12                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bijol','Udinese',9,21                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Kristensen','Roma',9,15                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Natan','Napoli',9,22                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Izzo','Monza',8,18                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Luperto','Empoli',8,10                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Rodriguez R.','Torino',8,10                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Martin','Genoa',8,20                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Mina','Fiorentina',8,18                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Demiral','Atalanta',8,11                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bellanova','Torino',8,25                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Singo','Torino',8,16                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Parisi','Fiorentina',8,20                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Dodo''','Fiorentina',8,26                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Hien','Verona',8,17                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Hysaj','Lazio',7,16                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','D''ambrosio','Monza',7,15                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Djimsiti','Atalanta',7,12                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Hateboer','Atalanta',7,14                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Palomino','Atalanta',7,13                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Marusic','Lazio',7,18                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Caldirola','Monza',7,10                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Kalulu','Milan',7,15                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bradaric','Salernitana',7,11                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Olivera','Napoli',7,20                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Lucumi''','Bologna',7,16                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Masina','Udinese',6,7                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','De Vrij','Inter',6,13                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Gyomber','Salernitana',6,7                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Alex Sandro','Rubentus',6,10                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Djidji','Torino',6,7                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Toljan','Sassuolo',6,9                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Zappa','Cagliari',6,12                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Vojvoda','Torino',6,16                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Llorente D.','Roma',6,16                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Martinez Quarta','Fiorentina',6,7               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Dragusin','Genoa',6,9                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Kamara H.','Udinese',6,10                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Viti','Sassuolo',6,7                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Gatti','Rubentus',6,18                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Gendrey','Lecce',6,8                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Beukema','Bologna',6,14                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Dossena','Cagliari',6,7                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Romagnoli S.','Frosinone',5,6                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Juan Jesus','Napoli',5,14                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Patric','Lazio',5,5                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Pezzella Giu.','Empoli',5,8                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Marchizza','Frosinone',5,5                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Lazzari','Lazio',5,13                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Lykogiannis','Bologna',5,8                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Kabasele','Udinese',5,5                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ranieri L.','Fiorentina',5,8                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Augello','Cagliari',5,10                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Gallo','Lecce',5,6                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Pirola','Salernitana',5,10                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Erlic','Sassuolo',5,10                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ismajli','Empoli',5,9                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Cambiaso','Rubentus',5,7                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Pongracic','Lecce',5,6                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Obert','Cagliari',5,6                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Tressoldi','Sassuolo',5,7                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Birindelli','Monza',5,5                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ehizibue','Udinese',5,6                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Zemura','Udinese',5,7                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Azzi','Cagliari',5,9                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Vogliacco','Genoa',5,6                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bonucci','Rubentus',4,5                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Sabelli','Genoa',4,6                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ferrari G.','Sassuolo',4,10                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Venuti','Lecce',4,5                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Kjaer','Milan',4,8                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Pellegrini Lu.','Rubentus',4,4                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Gunter','Verona',4,4                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Dawidowicz','Verona',4,5                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Soumaoro','Bologna',4,5                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Lovato','Salernitana',4,6                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Vina','Sassuolo',4,6                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Vasquez','Genoa',4,4                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Zanoli','Napoli',4,6                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ostigard','Napoli',4,9                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ebosele','Udinese',4,6                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Sambia','Salernitana',4,5                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bisseck','Inter',4,6                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Rugani','Rubentus',3,6                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','De Sciglio','Rubentus',3,6                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Goldaniga','Cagliari',3,3                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Florenzi','Milan',3,5                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Biraschi','Genoa',3,3                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bonifazi','Bologna',3,3                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bani','Genoa',3,5                               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Magnani','Verona',3,4                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Walukiewicz','Empoli',3,4                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Zortea','Atalanta',3,4                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Kumbulla','Roma',3,3                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Celik','Roma',3,5                               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Carboni A.','Monza',3,3                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Amione','Verona',3,5                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ruggeri','Atalanta',3,4                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Altare','Cagliari',3,4                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Stojanovic','Empoli',3,5                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Daniliuc','Salernitana',3,4                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Zima','Torino',3,4                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','De Winter','Genoa',3,6                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Hefti','Genoa',3,4                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Cittadini','Monza',3,4                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Cacace','Empoli',3,5                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Terracciano F.','Verona',3,5                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ebosse','Udinese',3,3                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Cabal','Verona',3,4                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','De Silvestri','Bologna',2,3                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Fazio','Salernitana',2,2                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Karsdorp','Roma',2,2                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Okoli','Atalanta',2,4                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ballo-Toure''','Milan',2,2                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Di Pardo','Cagliari',2,3                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Soppy','Atalanta',2,3                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Coppola D.','Verona',2,2                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Bronn','Salernitana',2,3                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Sosa','Bologna',2,2                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Gonzalez F.','Rubentus',2,4                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Dermaku','Lecce',1,1                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Tonelli','Empoli',1,2                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Capradossi','Cagliari',1,1                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Pajac','Genoa',1,2                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Monterisi','Frosinone',1,2                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Antov','Monza',1,1                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Amey','Bologna',1,1                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Gila','Lazio',1,2                               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Abankwah','Udinese',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Guessand A.','Udinese',1,1                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Guarino','Empoli',1,2                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Carboni F.','Monza',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Missori','Sassuolo',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Flamingo','Sassuolo',1,2                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Smajlovic','Lecce',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Kayode','Fiorentina',1,2                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Szyminski','Frosinone',1,1                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Oyono','Frosinone',1,8                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Klitten','Frosinone',1,1                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Matturro','Genoa',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','N''guessan','Torino',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Ferreira J.','Udinese',1,1                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Dorgu','Lecce',1,1                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Corazza','Bologna',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('D','Mateus Lusuardi','Frosinone',1,1                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Zaccagni','Lazio',28,195                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Koopmeiners','Atalanta',24,114             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Felipe Anderson','Lazio',23,144            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Rabiot','Rubentus',22,99                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Luis Alberto','Lazio',21,90                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Orsolini','Bologna',21,94                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Zielinski','Napoli',20,68                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Barella','Inter',20,86                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Chukwueze','Milan',19,97                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Pulisic','Milan',18,97                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Strefezza','Lecce',18,76                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Vlasic','Torino',18,70                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Frattesi','Inter',17,82                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Ferguson','Bologna',17,60                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Pellegrini Lo.','Roma',16,62                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','El Shaarawy','Roma',16,35                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Calhanoglu','Inter',16,51                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Samardzic','Udinese',16,50                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Lazovic','Verona',15,46                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Candreva','Salernitana',15,57               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Aouar','Roma',15,47                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Elmas','Napoli',15,55                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Kostic','Rubentus',15,45                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Baldanzi','Empoli',15,44                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Lovric','Udinese',15,53                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Kamada','Lazio',15,52                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Bonaventura','Fiorentina',14,38             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Politano','Napoli',14,50                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Pasalic','Atalanta',14,50                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Pessina','Monza',14,46                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Zambo Anguissa','Napoli',14,34              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Gudmundsson A.','Genoa',14,57               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Ciurria','Monza',14,42                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Mkhitaryan','Inter',13,42                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Renato Sanches','Roma',13,32                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Loftus-Cheek','Milan',13,29                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Lobotka','Napoli',13,27                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Fagioli','Rubentus',13,30                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Ikone','Fiorentina',13,28                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Bajrami','Sassuolo',13,36                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Ricci S.','Torino',13,25                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Pogba','Rubentus',12,32                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Locatelli','Rubentus',12,29                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Barak','Fiorentina',12,24                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Dominguez','Bologna',12,28                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Ilic','Torino',12,28                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Ndoye','Bologna',12,24                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Reijnders','Milan',12,35                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','De Roon','Atalanta',11,18                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Saponara','Verona',11,35                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Radonjic','Torino',11,30                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Bennacer','Milan',10,9                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Castrovilli','Fiorentina',10,11               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Weah','Rubentus',10,32                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Miranchuk','Atalanta',10,12                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Ederson D.s.','Atalanta',10,20              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Mboula','Verona',10,12                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Cristante','Roma',9,15                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Mandragora','Fiorentina',9,13                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Thorsby','Genoa',9,18                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Messias','Genoa',9,32                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Musah','Milan',9,18                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Matheus Henrique','Sassuolo',9,9                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Sabiri','Fiorentina',9,10                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Colpani','Monza',9,12                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Verdi','Torino',8,8                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Sottil','Fiorentina',8,10                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Lopez M.','Sassuolo',8,15                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Tameze','Torino',8,10                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Marin','Empoli',8,12                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Mckennie','Rubentus',8,11                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Gyasi','Empoli',8,16                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','EZalewski','Roma',8,10                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Coulibaly L.','Salernitana',8,10               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Mancosu','Cagliari',7,10                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Cataldi','Lazio',7,12                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Paredes','Roma',7,13                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Sensi','Inter',7,10                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Jankto','Cagliari',7,14                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Kastanos','Salernitana',7,12                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Walace','Udinese',7,9                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Arthur Melo','Fiorentina',7,10                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Nandez','Cagliari',7,20                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Amrabat','Fiorentina',7,19                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','De Ketelaere','Atalanta',7,32                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Gonzalez J.','Lecce',7,9                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Cajuste ','Napoli',7,14                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Krunic','Milan',6,10                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Vecino','Lazio',6,7                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Strootman','Genoa',6,8                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Gagliardini','Monza',6,12                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Duda','Verona',6,9                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Thorstvedt','Sassuolo',6,7                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Blin','Lecce',6,5                               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Fazzini','Empoli',6,10                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Moro N.','Bologna',6,6                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Boloca','Sassuolo',6,12                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Ramadani','Lecce',6,8                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','MGrassi','Empoli',5,6                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Badelj','Genoa',5,7                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Duncan','Fiorentina',5,5                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Machin','Monza',5,6                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Linetty','Torino',5,6                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Rovella','Lazio',5,10                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Saelemaekers','Milan',5,7                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Maldini','Empoli',5,9                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Brescianini','Frosinone',5,6                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Pobega','Milan',5,8                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Bove','Roma',5,7                                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Maleh','Lecce',5,4                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Aebischer','Bologna',5,6                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Frendrup','Genoa',5,10                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Miretti','Rubentus',5,11                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Marcos Antonio','Lazio',5,7                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Ranocchia F.','Empoli',5,6                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Fabbian','Inter',5,14                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Makoumbou','Cagliari',5,8                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Infantino','Fiorentina',5,10                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Kaba','Lecce',5,7                               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Deiola','Cagliari',4,5                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Mazzitelli','Frosinone',4,5                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Aramu','Genoa',4,9                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Haas','Empoli',4,4                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Quina','Udinese',4,4                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Racic','Sassuolo',4,8                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Hongla','Verona',4,4                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Romero L.','Milan',4,8                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Basic','Lazio',4,6                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Harroui','Frosinone',4,8                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Asllani','Inter',4,8                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Bohinen','Salernitana',4,6                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Iling Junior','Rubentus',4,12                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Oristanio','Cagliari',4,7              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Baez','Frosinone',3,6                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Garritano','Frosinone',3,4                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Gaetano','Napoli',3,4                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Jagiello','Genoa',3,5                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Henderson L.','Empoli',3,5                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Obiang','Sassuolo',3,3                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Maggiore','Salernitana',3,4                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Akpa Akpro','Lazio',3,3                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Volpato','Sassuolo',3,4                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Kourfalidis','Cagliari',3,4                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Hrustic','Verona',3,4                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Sulemana I.','Cagliari',3,4                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Zarraga','Udinese',3,4                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Camara E.','Udinese',3,4                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Rafia','Lecce',3,8                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Viola','Cagliari',2,4                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Coulibaly M.','Salernitana',2,3                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Vignato','Bologna',2,3                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Valoti','Monza',2,4                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Nicolussi Caviglia','Rubentus',2,2              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Adopo','Atalanta',2,4                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Carboni V.','Monza',2,4                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Barrenechea','Frosinone',2,4                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Belardinelli','Empoli',2,3                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Folorunsho','Verona',2,8                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Benassi','Fiorentina',1,1                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Rog','Cagliari',1,1                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Melegoni','Genoa',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Crociata','Empoli',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','MDemme','Napoli',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Urbanski','Bologna',1,2                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Pyyhtia','Bologna',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Pafundi','Udinese',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Helgason','Lecce',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Adli','Milan',1,3                               );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Vignato S.','Monza',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Zerbin','Napoli',1,1                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Ilkhan','Torino',1,1                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Faticanti','Roma',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Gineitis','Torino',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','El Azzouzi','Bologna',1,2                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Lella','Cagliari',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Amatucci','Fiorentina',1,1                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Haoudi','Frosinone',1,1                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Gelli','Frosinone',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Lipani','Sassuolo',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Saco','Napoli',1,1                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Joselito','Verona',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('C','Pagano','Roma',1,1                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Osimhen','Napoli',43,435                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Martinez L.','Inter',37,395                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Immobile','Lazio',32,332                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Rafael Leao','Milan',31,270                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Kvaratskhelia','Napoli',31,268             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Dybala','Roma',30,286                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Berardi','Sassuolo',30,272                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Vlahovic','Rubentus',28,319                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Lookman','Atalanta',26,185                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Dia','Salernitana',26,229                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Scamacca','Atalanta',25,160                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Sanabria','Torino',24,158                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Giroud','Milan',24,181                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Arnautovic','Inter',23,140                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Thuram','Inter',23,140                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Nzola','Fiorentina',23,110                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Retegui','Genoa',23,163                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Beto','Udinese',21,144                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Lauriente','Sassuolo',21,138              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Zapata D.','Atalanta',19,65                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Milik','Rubentus',18,95                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Chiesa','Rubentus',17,110                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Okafor','Milan',16,90                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Toure E.','Atalanta',16,100                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Beltran L.','Fiorentina',16,82              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Lapadula','Cagliari',15,41                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Abraham','Roma',15,58                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Caputo','Empoli',15,73                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Gonzalez N.','Fiorentina',15,93             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Muriel','Atalanta',14,30                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Caprari','Monza',14,54                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Deulofeu','Udinese',14,20                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Jovic','Fiorentina',14,15                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Barrow','Bologna',14,21                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Petagna','Monza',13,26                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Pinamonti','Sassuolo',13,48                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Simeone','Napoli',13,30                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Shomurodov','Cagliari',13,40                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Castellanos','Lazio',13,28                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Pedro','Lazio',12,18                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Cambiaghi','Atalanta',12,18                 );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Lozano','Napoli',12,25                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Henry','Verona',12,6                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Ngonge','Verona',12,47                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Isaksen','Lazio',12,21                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Correa','Inter',11,25                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Kean','Rubentus',11,20                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Thauvin','Udinese',11,16                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','"WA"Brekalo','Fiorentina',11,15           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Zirkzee','Bologna',11,10                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Mota','Monza',11,16                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Mulattieri','Sassuolo',11,24                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Brenner','Udinese',11,12                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Karamoh','Torino',10,6                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Raspadori','Napoli',10,35                   );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Colombo','Milan',10,6                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Almqvist','Lecce',10,10                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Belotti','Roma',9,28                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Defrel','Sassuolo',9,12                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Kouame','Fiorentina',9,8                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Djuric','Verona',9,10                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Di Francesco F.','Lecce',8,8                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Pellegri','Torino',8,10                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Luvumbo','Cagliari',8,9                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Botheim','Salernitana',8,10                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Banda','Lecce',8,10                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Solbakken','Roma',8,6                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Bonazzoli','Verona',7,8                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Piccoli','Empoli',7,9                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Success','Udinese',7,9                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Caso','Frosinone',6,16                         );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Lucca','Udinese',6,7                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Coda M.','Genoa',5,5                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Cancellieri','Empoli',5,10                     );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Alvarez A.','Sassuolo',5,5                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Pavoletti','Cagliari',4,6                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Soule''','Rubentus',4,5                    );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Cuni','Frosinone',4,8                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Origi','Milan',3,1                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Esposito','Inter',3,6                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Seck','Torino',3,3                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Kvernadze','Frosinone',3,6                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Puscas','Genoa',2,2                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Kallon','Verona',2,2                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Ake'' M.','Udinese',1,2                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Braaf','Verona',1,1                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Kaio Jorge','Rubentus',1,2                      );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Ekuban','Genoa',1,2                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Ceide','Sassuolo',1,1                           );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Voelkerling Persson','Lecce',1,1                );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Valencia D.','Salernitana',1,1                  );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Ekong','Empoli',1,1                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Vivaldo','Udinese',1,1                          );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Bidaoui','Frosinone',1,1                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Borrelli','Frosinone',1,1                       );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Yalcin','Genoa',1,1                             );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Maric','Monza',1,1                              );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Shpendi S.','Empoli',1,1                        );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Burnete','Lecce',1,1                            );
INSERT INTO PLAYERS (ROLE, NAME, TEAM, QUOTE, FVM) VALUES ('A','Corfitzen','Lecce',1,1                          );